### ISSUE TITLE
is_latest_version flag is set on the most out of date row

### ISSUE THREAD

**Issue by dlubawy** [fivetran/dbt_twitter_source#14]
Use of ascending order on the `updated_timestamp` column means that the oldest timestamp is in row 1 and the last updated row is in the last row when using `row_number()`. This means that the oldest row gets flagged as `is_latest_version` with the conditional statement `= 1`. This is found throughout the staging models such as [stg_twitter_ads__line_item_history](https://github.com/fivetran/dbt_twitter_source/blob/main/models/stg_twitter_ads__line_item_history.sql#L25).

Environment tested: BigQuery

Suggested fix: switch to descending order.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @dlubawy thank you so much for raising this issue with our team! I would agree with you that this is incorrect and should be addressed within our package to reflect the true `is_latest_version` record. Additionally, I did validate this on my end and see that the most recent record is in fact incorrectly being calculated.

It looks like the `asc` logic is used in all the other history models of this package and should be updated.
- [stg_twitter_ads__line_item_history](https://github.com/fivetran/dbt_twitter_source/blob/main/models/stg_twitter_ads__line_item_history.sql)
- [stg_twitter_ads__promoted_tweet_history](https://github.com/fivetran/dbt_twitter_source/blob/main/models/stg_twitter_ads__promoted_tweet_history.sql)
- [stg_twitter_ads__account_history](https://github.com/fivetran/dbt_twitter_source/blob/main/models/stg_twitter_ads__account_history.sql)
- [stg_twitter_ads__campaign_history](https://github.com/fivetran/dbt_twitter_source/blob/main/models/stg_twitter_ads__campaign_history.sql)

Since you identified this issue, I was wondering if you were open to creating a PR to address this change and contribute to the package code base? If so, I am happy to help with any questions you may have with contributing. Otherwise, my team is happy to address this in the next release.

**Comment by fivetran-joemarkiewicz** [comment]
@dlubawy thanks so much for raising this with our team and contributing the fix in your PR! 🙌 

These changes were just included in the latest release of the package. You should see them live on the dbt hub at the top of the hour. 

Thank you again for opening the PR. These packages are constantly made better by community members like yourself. We greatly appreciate your contribution 😄
